server:
  port: 8084

spring:
  application:
    name:  COACHIFY-GATEWAY
   
  cloud:  
    gateway:
      routes:
        - id: CUSTOMER
          uri: lb://CUSTOMER
          predicates:
            - Path= /Coachify/customer/**
        
        - id: CUSTOMER
          uri: lb://COACHES
          predicates:
            - Path= /Coachify/coaches/**
            
        - id: CUSTOMER
          uri: lb://APPOINTMENT
          predicates:
            - Path= /Coachify/appointment/**
      

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    